  -- Preview first
  SELECT COUNT(*) AS records_to_update
  FROM DOCUMENTHISTORY dh
  JOIN WEBUSER wu ON dh.TOUSER_ID = wu.ID
  WHERE dh.TOUSER_ID IS NOT NULL
    AND dh.TOINSTITUTION_ID IS NULL
    AND dh.HISTORYTYPE = 'Letter_Copy_or_Forward';

  -- Then update
  UPDATE DOCUMENTHISTORY dh
  JOIN WEBUSER wu ON dh.TOUSER_ID = wu.ID
  SET dh.TOINSTITUTION_ID = wu.INSTITUTION_ID
  WHERE dh.TOUSER_ID IS NOT NULL
    AND dh.TOINSTITUTION_ID IS NULL
    AND dh.HISTORYTYPE = 'Letter_Copy_or_Forward';